<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EUnavailability extends \EUnavailability implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'car' => [parent::class, 'car', null, 16],
        "\0".parent::class."\0".'end' => [parent::class, 'end', null, 16],
        "\0".parent::class."\0".'idUnavailability' => [parent::class, 'idUnavailability', null, 16],
        "\0".parent::class."\0".'start' => [parent::class, 'start', null, 16],
        'car' => [parent::class, 'car', null, 16],
        'end' => [parent::class, 'end', null, 16],
        'idUnavailability' => [parent::class, 'idUnavailability', null, 16],
        'start' => [parent::class, 'start', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
