<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EImage extends \EImage implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'car' => [parent::class, 'car', null, 16],
        "\0".parent::class."\0".'idImage' => [parent::class, 'idImage', null, 16],
        "\0".parent::class."\0".'imageData' => [parent::class, 'imageData', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'size' => [parent::class, 'size', null, 16],
        "\0".parent::class."\0".'types' => [parent::class, 'types', null, 16],
        'car' => [parent::class, 'car', null, 16],
        'idImage' => [parent::class, 'idImage', null, 16],
        'imageData' => [parent::class, 'imageData', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'size' => [parent::class, 'size', null, 16],
        'types' => [parent::class, 'types', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
