<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EUser extends \EUser implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'address' => [parent::class, 'address', null, 8],
        "\0".'*'."\0".'city' => [parent::class, 'city', null, 8],
        "\0".'*'."\0".'description' => [parent::class, 'description', null, 8],
        "\0".'*'."\0".'email' => [parent::class, 'email', null, 8],
        "\0".'*'."\0".'firstname' => [parent::class, 'firstname', null, 8],
        "\0".'*'."\0".'idUser' => [parent::class, 'idUser', null, 8],
        "\0".'*'."\0".'isVerified' => [parent::class, 'isVerified', null, 8],
        "\0".'*'."\0".'password' => [parent::class, 'password', null, 8],
        "\0".'*'."\0".'phone' => [parent::class, 'phone', null, 8],
        "\0".'*'."\0".'role' => [parent::class, 'role', null, 8],
        "\0".'*'."\0".'surname' => [parent::class, 'surname', null, 8],
        "\0".'*'."\0".'username' => [parent::class, 'username', null, 8],
        "\0".'*'."\0".'zipCode' => [parent::class, 'zipCode', null, 8],
        'address' => [parent::class, 'address', null, 8],
        'city' => [parent::class, 'city', null, 8],
        'description' => [parent::class, 'description', null, 8],
        'email' => [parent::class, 'email', null, 8],
        'firstname' => [parent::class, 'firstname', null, 8],
        'idUser' => [parent::class, 'idUser', null, 8],
        'isVerified' => [parent::class, 'isVerified', null, 8],
        'password' => [parent::class, 'password', null, 8],
        'phone' => [parent::class, 'phone', null, 8],
        'role' => [parent::class, 'role', null, 8],
        'surname' => [parent::class, 'surname', null, 8],
        'username' => [parent::class, 'username', null, 8],
        'zipCode' => [parent::class, 'zipCode', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
