<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ECarForSale extends \ECarForSale implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'Km0OrNew' => [parent::class, 'Km0OrNew', null, 8],
        "\0".'*'."\0".'available' => [parent::class, 'available', null, 8],
        "\0".'*'."\0".'brand' => [parent::class, 'brand', null, 8],
        "\0".'*'."\0".'color' => [parent::class, 'color', null, 8],
        "\0".'*'."\0".'displacement' => [parent::class, 'displacement', null, 8],
        "\0".'*'."\0".'fuelType' => [parent::class, 'fuelType', null, 8],
        "\0".'*'."\0".'horsepower' => [parent::class, 'horsepower', null, 8],
        "\0".'*'."\0".'idAuto' => [parent::class, 'idAuto', null, 8],
        "\0".'*'."\0".'model' => [parent::class, 'model', null, 8],
        "\0".'*'."\0".'photo' => [parent::class, 'photo', null, 8],
        "\0".'*'."\0".'price' => [parent::class, 'price', null, 8],
        "\0".'*'."\0".'saleOrder' => [parent::class, 'saleOrder', null, 8],
        "\0".'*'."\0".'saled' => [parent::class, 'saled', null, 8],
        "\0".'*'."\0".'seats' => [parent::class, 'seats', null, 8],
        'Km0OrNew' => [parent::class, 'Km0OrNew', null, 8],
        'available' => [parent::class, 'available', null, 8],
        'brand' => [parent::class, 'brand', null, 8],
        'color' => [parent::class, 'color', null, 8],
        'displacement' => [parent::class, 'displacement', null, 8],
        'fuelType' => [parent::class, 'fuelType', null, 8],
        'horsepower' => [parent::class, 'horsepower', null, 8],
        'idAuto' => [parent::class, 'idAuto', null, 8],
        'model' => [parent::class, 'model', null, 8],
        'photo' => [parent::class, 'photo', null, 8],
        'price' => [parent::class, 'price', null, 8],
        'saleOrder' => [parent::class, 'saleOrder', null, 8],
        'saled' => [parent::class, 'saled', null, 8],
        'seats' => [parent::class, 'seats', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
